services:
  nginx:
    image: nginx:latest
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    expose:
      - "80"
    ports:
      - "8145:80"
    volumes:
      - /root/filesharingfe/build:/usr/share/nginx/html
